apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  selector:
    prometheus: prometheus-persistant
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: web
    #loadBalancerIP: 192.168.0.245

